# Generated by Django 3.1 on 2020-12-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201208_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_id',
            field=models.CharField(db_index=True, editable=False, max_length=10, unique=True),
        ),
    ]
